spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo-12-bbd-oo2-2021?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
server:
  error:
    whitelabel:
        enabled: false