spring:
  datasource:
    url: jdbc:mysql://localhost/30-login-3
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

